### ISSUE TITLE
HTTPError (Api-limit reached?)

### ISSUE THREAD

**Issue by sokki** [sindresorhus/alfred-emoj#15]
I can't use the workflow anymore :(

```
[2017-08-10 15:04:02][ERROR: input.scriptfilter] Code 1: {
	"items": [
		{
			"title": "HTTPError\n    at stream.catch.then.data (/Users/tsc/.nvm/versions/node/v8.1.3/lib/node_modules/alfred-emoj/node_modules/got/index.js:123:13)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:169:7)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nHTTPError\n    at stream.catch.then.data (/Users/tsc/.nvm/versions/node/v8.1.3/lib/node_modules/alfred-emoj/node_modules/got/index.js:123:13)\n    at <anonymous>\n```\n\n-\nEmoj 1.0.0\nAlfred 3.3.2\ndarwin x64 16.7.0",
				"largetype": "HTTPError\n    at stream.catch.then.data (/Users/tsc/.nvm/versions/node/v8.1.3/lib/node_modules/alfred-emoj/node_modules/got/index.js:123:13)\n    at <anonymous>"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
```

**Comment by paulmolluzzo** [comment]
It looks like the API for get dango has changed, and now it starts at $100/month. http://getdango.com/api/
 ☹️ 

I don't know of another free emoji API, but this workflow hinges on having access to one.

**Comment by paulmolluzzo** [comment]
Seems to be working for me now with no changes. Can you check too @sokki and close if it's fixed?

**Comment by SamVerschueren** [comment]
Works for me as well

**Comment by sokki** [comment]
Works again, thanks 👍

**Comment by SamVerschueren** [comment]
Weird stuff going on with the API. Doesn't seem to work anymore. Related https://github.com/sindresorhus/emoj/issues/31

**Comment by seanonthenet** [comment]
Was fun while it lasted

**Comment by sindresorhus** [comment]
Closing as it still works, but it's not super reliable.
