### ISSUE TITLE
npm i -g alfred-emoj failed with Alfred 4

### ISSUE THREAD

**Issue by yuchunc** [sindresorhus/alfred-emoj#22]
Hi, 

I had been using alfred-emoj with Alfred 3 for sometime, recently I switched to Alfred 4 after reinstalling my laptop. `npm i -g alfred-emoj` failed to install with this message:

```
{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/mickey/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/Users/mickey/.asdf/installs/nodejs/10.16.0/.npm/lib/node_modules/alfred-emoj/node_modules/resolve-alfred-prefs/index.js:15:10)


    at makeError (/Users/mickey/.asdf/installs/nodejs/10.16.0/.npm/lib/node_modules/alfred-emoj/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/mickey/.asdf/installs/nodejs/10.16.0/.npm/lib/node_modules/alfred-emoj/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout: '',
  stderr:
   'Error: Alfred preferences not found at location /Users/mickey/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/Users/mickey/.asdf/installs/nodejs/10.16.0/.npm/lib/node_modules/alfred-emoj/node_modules/resolve-alfred-prefs/index.js:15:10)\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false,
  killed: false }
```

I looked in to my finder and seems like Alfred 4 preference has been renamed from `com.runningwithcrayons.Alfred-Preferences-3.plist` to `com.runningwithcrayons.Alfred-Preferences.plist`.

**Comment by yuchunc** [comment]
related to https://github.com/sindresorhus/alfy/issues/110

**Comment by LitoMore** [comment]
We released a patch update to fix this bug. You could rerun `npm i -g alfred-emoj` to get it to work. 😄
