### ISSUE TITLE
Still Unable to Read Preferences in Alfred 4

### ISSUE THREAD

**Issue by ohong** [sindresorhus/alfred-emoj#23]
Related to #22, but this still seems to be unsolved for me. Despite `alfred-link`, the install script is still looking for `Alfred-Preferences-3.plist`. Could this be caused by the fact that I store my Alfred preferences in a different directory (e.g. Dropbox for syncing)?

```bash
Error: Command failed: alfred-link
Error: Permission denied to read Alfred preferences at location /Users/ohong/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at module.exports (/Users/ohong/.nvm/versions/node/v12.8.0/lib/node_modules/alfred-emoj/node_modules/resolve-alfred-prefs/index.js:44:9)

    at makeError (/Users/ohong/.nvm/versions/node/v12.8.0/lib/node_modules/alfred-emoj/node_modules/execa/index.js:174:9)
    at /Users/ohong/.nvm/versions/node/v12.8.0/lib/node_modules/alfred-emoj/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  code: 1,
  stdout: '',
  stderr: 'Error: Permission denied to read Alfred preferences at location /Users/ohong/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at module.exports (/Users/ohong/.nvm/versions/node/v12.8.0/lib/node_modules/alfred-emoj/node_modules/resolve-alfred-prefs/index.js:44:9)\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false,
  killed: false
}
```

**Comment by sindresorhus** [comment]
Can you move this issue to https://github.com/SamVerschueren/alfred-link? I cannot do anything about this here.
