### ISSUE TITLE
Error: Cannot find module '.'

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/alfred-emoj#24]
not sure if this is a problem on my side, but I cannot install the latest version of `alfred-emoj`:
```
lucaban@Golden-Birdie ~> npm i -g alfred-emoj@latest

> alfred-emoj@2.0.0 preuninstall /usr/local/lib/node_modules/alfred-emoj
> alfy-cleanup

Error: Command failed: alfred-unlink
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '.'
Require stack:
- /usr/local/lib/node_modules/alfred-emoj/node_modules/.bin/alfred-unlink
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-emoj/node_modules/.bin/alfred-unlink:3:20)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/alfred-emoj/node_modules/.bin/alfred-unlink'
  ]
}


    at makeError (/usr/local/lib/node_modules/alfred-emoj/node_modules/execa/index.js:174:9)
    at /usr/local/lib/node_modules/alfred-emoj/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 1,
  stdout: '',
  stderr: 'internal/modules/cjs/loader.js:800\n' +
    '    throw err;\n' +
    '    ^\n' +
    '\n' +
    "Error: Cannot find module '.'\n" +
    'Require stack:\n' +
    '- /usr/local/lib/node_modules/alfred-emoj/node_modules/.bin/alfred-unlink\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:690:27)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:852:19)\n' +
    '    at require (internal/modules/cjs/helpers.js:74:18)\n' +
    '    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-emoj/node_modules/.bin/alfred-unlink:3:20)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:959:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:815:32)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:727:14)\n' +
    '    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {\n' +
    "  code: 'MODULE_NOT_FOUND',\n" +
    '  requireStack: [\n' +
    "    '/usr/local/lib/node_modules/alfred-emoj/node_modules/.bin/alfred-unlink'\n" +
    '  ]\n' +
    '}\n',
  failed: true,
  signal: null,
  cmd: 'alfred-unlink',
  timedOut: false,
  killed: false
}
```

**Comment by sindresorhus** [comment]
Closing as I don't think this is relevant anymore.
